version: "3"
services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - "27000:27017"
    env_file: .env.mongo
    volumes:
      - ./bin/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
  mongodb-time:
    image: mongo
    restart: always
    container_name: timeseries-mongo
    ports:
      - "27010:27017"
    env_file: .env.mongo
    volumes:
      - ./bin/init-mongo-timeseries.sh:/docker-entrypoint-initdb.d/init-mongo.sh
